### ISSUE TITLE
Cannot find module when using handler with Gulp

### ISSUE THREAD

**Issue by extrabright** [electerious/rosid-handler-njk#27]
In my gulp file I added:

const handler = require('rosid-handler-njk')

```
var compileFiles = function(done) {
	var res = handlerRosid('./src/components/aaa/aaa.njk').then((data) => {
		console.log(data);
	})
	done();
}
```

It works when I don't have a `data.js` file next to the `njk` component. But when I add the data file,  I get the following error when trying to compile files using rosid handler:

```
node:events:368
      throw er; // Unhandled 'error' event
  
Error: Cannot find module 'src/components/filename/filename.data.js'

Emitted 'error' event on Domain instance at:
    at emit (node:internal/process/promises:134:35)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32) {
  code: 'MODULE_NOT_FOUND',
}
```

I know you are not currently maintaining this, but I hope you could give me a hint how to solve this :)

**Comment by electerious** [comment]
Hey @alexisenache, this is strange. Is `src/components/filename/filename.data.js` the correct path? Maybe it doesn't work because the path is relative and rosid-handler-njk starts from a different entry point?

Here's where rosid-handler-njk calls the require function: https://github.com/electerious/rosid-handler-njk/blob/master/src/data.js#L40
The require inside require-data: https://github.com/electerious/require-data/blob/master/src/index.js

Could be worth to add some console.logs to check if the path is correct. Hope that helps.

**Comment by alexisenache** [comment]
Hi @electerious, seems that was the problem. I used `src` to specify the root folder and then in `data`, I added the relative path to the data file. So, it works now. 

Thanks!
